task_name: llm_cognitive_flexibility_revisited
output_type: generate_until_multiturn
gen_kwargs:
  do_sample: False
  max_new_tokens: 100
experiments:
  - llm_cognitive_flexibility_wcst_revisited
  - llm_cognitive_flexibility_lnt_revisited