executive_functions:
  planning_decision_making:
    alias: "Planning"
  causal_reasoning:
    alias: "Causal R."
  logical_numerical_reasoning:
    alias: "Logic R."
  commonsense_reasoning:
    alias: "Commonsense R."
core_executive_functions:
  cognitive_flexibility:
    alias: "Cog. Flex."
  working_memory:
    alias: "Working Mem."
social_emotional_cognition:
  social_commonsense_reasoning:
    alias: "Social R."
  theory_of_mind:
    alias: "Theory of Mind"
  emotional_intelligence:
    alias: "Emo. Int."
  pragmatics:
    alias: "Pragmatics"
  attribution_judgment:
    alias: "Attr./Judgment"


