meta-llama__Llama-3.1-8B-Instruct:
  params: 8B
  family: Llama3
meta-llama__Llama-3.3-70B-Instruct:
  params: 70B
  family: Llama3
Qwen__Qwen2.5-7B-Instruct:
  params: 7B
  family: Qwen2.5
Qwen__Qwen2.5-32B-Instruct:
  params: 32B
  family: Qwen2.5
Qwen__Qwen2.5-72B-Instruct:
  params: 72B
  family: Qwen2.5
allenai__OLMo-2-1124-7B-Instruct:
  params: 7B
  family: OLMo2
allenai__OLMo-2-1124-13B-Instruct:
  params: 13B
  family: OLMo2
tiiuae__Falcon3-10B-Instruct:
  params: 10B
  family: Falcon3
#CohereForAI__aya-expanse-32b:
#  params: 32B
#google__gemma-2-9b-it:
#  params: 9B

