capabilities:
  functional: [ "commonsense_reasoning", "planning_decision_making", "logical_numerical_reasoning", "causal_reasoning","social_commonsense_reasoning", "theory_of_mind", "emotional_intelligence", "pragmatics", "working_memory"]
  formal: [ "semantics", "predicate_argument_structure", "negation", "metalinguistic" ]

groups:
    logiqa2:
        logiqa2:
            alias: "LogiQA 2.0"
            functional: [ "logical_numerical_reasoning" ]
            formal: [ ]
            functional_groups: [ "executive_functions"]
            task_type: [ "multiple_choice" ]
            backend: "harness"
            main_task: True
    hendrycks_math:
        hendrycks_math:
            alias: "MATH"
            functional: [ "logical_numerical_reasoning" ]
            formal: [ ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "open_question" ]
            backend: "harness"
            main_task: True
        hendrycks_math_algebra:
            alias: "MATH Algebra"
            functional: [ "logical_numerical_reasoning" ]
            formal: [ ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "open_question" ]
            backend: "harness"
        hendrycks_math_counting_prob:
            alias: "MATH Counting and Prob."
            functional: [ "logical_numerical_reasoning" ]
            formal: [ ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "open_question" ]
            backend: "harness"
        hendrycks_geometry:
            alias: "MATH Geometry"
            functional: [ "logical_numerical_reasoning" ]
            formal: [ ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "open_question" ]
            backend: "harness"
        hendrycks_intermediate_algebra:
            alias: "MATH Intermediate Algebra"
            functional: [ "logical_numerical_reasoning" ]
            formal: [ ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "open_question" ]
            backend: "harness"
        hendrycks_math_num_theory:
            alias: "MATH Num. Theory"
            functional: [ "logical_numerical_reasoning" ]
            formal: [ ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "open_question" ]
            backend: "harness"
        hendrycks_math_prealgebra:
            alias: "MATH Prealgebra"
            functional: [ "logical_numerical_reasoning" ]
            formal: [ ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "open_question" ]
            backend: "harness"
        hendrycks_math_precalc:
            alias: "MATH Precalc."
            functional: [ "logical_numerical_reasoning" ]
            formal: [ ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "open_question" ]
            backend: "harness"
    ewok_minimal_pairs:
        ewok_minimal_pairs:
            alias: "EWoK Minimal Pairs"
            functional: [ "commonsense_reasoning", "social_commonsense_reasoning" ]
            formal: [ "negation" ]
            functional_groups: [ "executive_functions", "social_emotional_cognition" ]
            task_type: [ "minimal_pairs_logprobs" ]
            backend: "playeval_framework"
            main_task: True
        ewok_minimal_pairs_agent_properties:
            alias: "EWoK Minimal Pairs Agent Properties"
            functional: [ "commonsense_reasoning" ]
            formal: [ "negation" ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "minimal_pairs_logprobs" ]
            backend: "playeval_framework"
        ewok_minimal_pairs_social_relations:
            alias: "EWoK Minimal Pairs Social Relations"
            functional: [ "social_commonsense_reasoning" ]
            formal: [ "negation" ]
            functional_groups: ["social_emotional_cognition" ]
            task_type: [ "minimal_pairs_logprobs" ]
            backend: "playeval_framework"
        ewok_minimal_pairs_material_dynamics:
            alias: "EWoK Minimal Pairs Material Dynamics"
            functional: [ "commonsense_reasoning"]
            formal: [ "negation" ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "minimal_pairs_logprobs" ]
            backend: "playeval_framework"
        ewok_minimal_pairs_physical_relations:
            alias: "EWoK Minimal Pairs Physical Relations"
            functional: [ "commonsense_reasoning"]
            formal: [ "negation" ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "minimal_pairs_logprobs" ]
            backend: "playeval_framework"
        ewok_minimal_pairs_physical_interactions:
            alias: "EWoK Minimal Pairs Physical Interactions"
            functional: [ "commonsense_reasoning"]
            formal: [ "negation" ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "minimal_pairs_logprobs" ]
            backend: "playeval_framework"
        ewok_minimal_pairs_spatial_relations:
            alias: "EWoK Minimal Pairs Spatial Relations"
            functional: [ "commonsense_reasoning"]
            formal: [ "negation" ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "minimal_pairs_logprobs" ]
            backend: "playeval_framework"
        ewok_minimal_pairs_quantitative_properties:
            alias: "EWoK Minimal Pairs Quantitative Properties"
            functional: [ "commonsense_reasoning" ]
            formal: [ "negation" ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "minimal_pairs_logprobs" ]
            backend: "playeval_framework"
        ewok_minimal_pairs_social_properties:
            alias: "EWoK Minimal Pairs Social Properties"
            functional: [ "social_commonsense_reasoning"]
            formal: [ "negation" ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "minimal_pairs_logprobs" ]
            backend: "playeval_framework"
        ewok_minimal_pairs_social_interactions:
            alias: "EWoK Minimal Pairs Social Interactions"
            functional: [ "social_commonsense_reasoning" ]
            formal: [ "negation" ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "minimal_pairs_logprobs" ]
            backend: "playeval_framework"
        ewok_minimal_pairs_material_properties:
            alias: "EWoK Minimal Pairs Material Properties"
            functional: [ "commonsense_reasoning"]
            formal: [ "negation" ]
            functional_groups: [ "excecutive_functions" ]
            task_type: [ "minimal_pairs_logprobs" ]
            backend: "playeval_framework"
    fantom:
        fantom_full:
            alias: "FANToM"
            functional: [ "theory_of_mind" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "multiple_choice" , "open_question" ]
            backend: "harness"
            main_task: True
        fantom_full_answerability_binary:
            alias: "FANToM Answerability B"
            functional: [ "theory_of_mind" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "multiple_choice" ]
            backend: "harness"
        fantom_full_answerability_list:
            alias: "FANToM Answerability L"
            functional: [ "theory_of_mind" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "open_question" ]
            backend: "harness"
        fantom_full_belief_choice:
            alias: "FANToM Belief Choice"
            functional: [ "theory_of_mind" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "multiple_choice" ]
            backend: "harness"
        fantom_belief_gen:
            alias: "FANToM Belief Gen"
            functional: [ "theory_of_mind" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "open_question" ]
            backend: "harness"
        fantom_full_fact:
            alias: "FANToM Full Fact"
            functional: [ "theory_of_mind" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "open_question" ]
            backend: "harness"
        fantom_full_infoaccessibility_binary:
            alias: "FANToM Infoaccessibility B"
            functional: [ "theory_of_mind" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "multiple_choice" ]
            backend: "harness"
        fantom_full_infoaccessibility_list:
            alias: "FANToM Infoaccessibility L"
            functional: [ "theory_of_mind" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "open_question" ]
            backend: "harness"
    dnli:
        dnli:
            alias: "DNLI"
            functional: [ "pragmatics" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "nli" ]
            backend: "playeval_framework"
            main_task: True
    eq_bench:
        eq_bench:
            alias: "EQBench"
            functional: [ "emotional_intelligence" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "likert" ]
            backend: "harness"
    lm_pragmatics:
        lm_pragmatics:
            alias: "LM-Pragmatics"
            functional: [ "pragmatics" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "multiple_choice" ]
            backend: "harness"
            main_task: True
        coherence:
            alias: "LM-Pragmatics Coherence"
            functional: [ "pragmatics" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "multiple_choice" ]
            backend: "harness"
        deceits:
            alias: "LM-Pragmatics Deceits"
            functional: [ "pragmatics" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "multiple_choice" ]
            backend: "harness"
        humour:
            alias: "LM-Pragmatics Humour"
            functional: [ "pragmatics" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "multiple_choice" ]
            backend: "harness"
        irony:
            alias: "LM-Pragmatics Irony"
            functional: [ "pragmatics" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "multiple_choice" ]
            backend: "harness"
        maxims:
            alias: "LM-Pragmatics Maxims"
            functional: [ "pragmatics" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "multiple_choice" ]
            backend: "harness"
        metaphor:
            alias: "LM-Pragmatics Metaphor"
            functional: [ "pragmatics" ]
            formal: [ ]
            functional_groups: [ "social_emotional_cognition" ]
            task_type: [ "multiple_choice" ]
            backend: "harness"
    wm:
        wm:
            alias: "WM"
            functional: [ "working_memory" ]
            formal: [ ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "open_question" ] #TODO
            backend: "harness"