logiqa2:
    logiqa2:
        alias: "LogiQA 2.0"
        functional: [ "logical_numerical_reasoning" ]
        functional_groups: [ "executive_functions"]
        task_type: [ "multiple_choice" ]
        backend: "harness"
        main_task: True
        random_baseline: 0.25
        higher_bound: 1
ewok_minimal_pairs:
    ewok_minimal_pairs:
        alias: "EWoK Minimal Pairs"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: True
        random_baseline: 0.5
        higher_bound: 1
    ewok_minimal_pairs_agent_properties:
        alias: "EWoK Minimal Pairs Agent Properties"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    ewok_minimal_pairs_social_relations:
        alias: "EWoK Minimal Pairs Social Relations"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    ewok_minimal_pairs_material_dynamics:
        alias: "EWoK Minimal Pairs Material Dynamics"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    ewok_minimal_pairs_physical_relations:
        alias: "EWoK Minimal Pairs Physical Relations"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    ewok_minimal_pairs_physical_interactions:
        alias: "EWoK Minimal Pairs Physical Interactions"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    ewok_minimal_pairs_physical_dynamics:
        alias: "EWoK Minimal Pairs Physical Dynamics"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    ewok_minimal_pairs_spatial_relations:
        alias: "EWoK Minimal Pairs Spatial Relations"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    ewok_minimal_pairs_quantitative_properties:
        alias: "EWoK Minimal Pairs Quantitative Properties"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    ewok_minimal_pairs_social_properties:
        alias: "EWoK Minimal Pairs Social Properties"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    ewok_minimal_pairs_social_interactions:
        alias: "EWoK Minimal Pairs Social Interactions"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    ewok_minimal_pairs_material_properties:
        alias: "EWoK Minimal Pairs Material Properties"
        functional: []
        functional_groups: [ "extra" ]
        formal: [ ]
        task_type: [ "minimal_pairs_logprobs" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
fantom:
    fantom_full:
        alias: "FANToM"
        functional: [ "theory_of_mind" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "multiple_choice" , "open_question" ]
        backend: "harness"
        main_task: True
        random_baseline: 0 # TODO
        higher_bound: 1
    fantom_full_answerability_binary:
        alias: "FANToM Answerability Y/N"
        functional: [ "theory_of_mind" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "multiple_choice" ]
        backend: "harness"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    fantom_full_answerability_list:
        alias: "FANToM Answerability L"
        functional: [ "theory_of_mind" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "open_question" ]
        backend: "harness"
        main_task: False
        random_baseline: 0.03 # (1/32) since only one combination of names of 5 characters is the correct one
        higher_bound: 1
    #fantom_full_belief_choice:
    #    alias: "FANToM Belief Choice"
    #    functional: [ "theory_of_mind" ]
    #    formal: [ ]
    #    functional_groups: [ "social_emotional_cognition" ]
    #    task_type: [ "multiple_choice" ]
    #    backend: "harness"
    #    main_task: False
    #    random_baseline: 0.5
    #    higher_bound: 1
    fantom_full_belief_gen:
        alias: "FANToM Belief Dist"
        functional: [ "theory_of_mind" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "open_question" ]
        backend: "harness"
        main_task: False
        random_baseline: 0
        higher_bound: 1
    fantom_full_fact:
        alias: "FANToM Full Fact"
        functional: [ "theory_of_mind" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "open_question" ]
        backend: "harness"
        main_task: False
        random_baseline: 0
        higher_bound: 1
    fantom_full_infoaccessibility_binary:
        alias: "FANToM Infoaccessibility Y/N"
        functional: [ "theory_of_mind" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "multiple_choice" ]
        backend: "harness"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    fantom_full_infoaccessibility_list:
        alias: "FANToM Infoaccessibility L"
        functional: [ "theory_of_mind" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "open_question" ]
        backend: "harness"
        main_task: False
        random_baseline: 0.03
        higher_bound: 1
#dnli:
#    dnli:
#        alias: "DNLI"
#        functional: [ "pragmatics" ]
#        formal: [ ]
#        functional_groups: [ "social_emotional_cognition" ]
#        task_type: [ "nli" ]
#        backend: "playeval_framework"
#        main_task: True
eq_bench:
    eq_bench:
        alias: "EQBench"
        functional: [ "emotional_intelligence" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "likert" ]
        main_task: True
        backend: "harness"
        random_baseline: 0
        higher_bound: 100
lm_pragmatics:
    lm_pragmatics:
        alias: "LM-Pragmatics"
        functional: [ "pragmatics" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "multiple_choice" ]
        backend: "harness"
        main_task: False
        random_baseline: 0.3
        higher_bound: 1
    coherence:
        alias: "LM-Pragmatics Coherence"
        functional: [ "pragmatics" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "multiple_choice" ]
        backend: "harness"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    deceits:
        alias: "LM-Pragmatics Deceits"
        functional: [ "pragmatics" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "multiple_choice" ]
        backend: "harness"
        main_task: False
        random_baseline: 0.25
        higher_bound: 1
    humour:
        alias: "LM-Pragmatics Humour"
        functional: [ "pragmatics" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "multiple_choice" ]
        backend: "harness"
        main_task: True
        random_baseline: 0.2
        higher_bound: 1
    irony:
        alias: "LM-Pragmatics Irony"
        functional: [ "pragmatics" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "multiple_choice" ]
        backend: "harness"
        main_task: True
        random_baseline: 0.25
        higher_bound: 1
    maxims:
        alias: "LM-Pragmatics Maxims"
        functional: [ "pragmatics" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "multiple_choice" ]
        backend: "harness"
        main_task: True
        random_baseline: 0.25
        higher_bound: 1
    metaphor:
        alias: "LM-Pragmatics Metaphor"
        functional: [ "pragmatics" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "multiple_choice" ]
        backend: "harness"
        main_task: True
        random_baseline: 0.2
        higher_bound: 1
    indirect_speech:
        alias: "LM-Pragmatics Indirect Speech"
        functional: [ "pragmatics" ]
        formal: [ ]
        functional_groups: [ "social_emotional_cognition" ]
        task_type: [ "multiple_choice" ]
        backend: "harness"
        main_task: True
        random_baseline: 0.25
        higher_bound: 1
wm:
    #wm:
    #    alias: "WM"
    #    functional: [ "working_memory" ]
    #    formal: [ ]
    #    functional_groups: [ "executive_functions" ]
    #     task_type: [ "open_question" ]
    #    main_task: True
    #    backend: "playeval_framework"
    #    random_baseline: 0.5
    #    higher_bound: 1
    wm_spatial_3*3_1back:
        alias: "WM Spatial 3*3 N-1"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_3*3_2back:
        alias: "WM Spatial 3*3 N-2"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_3*3_3back:
        alias: "WM Spatial 3*3 N-3"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_4*4_1back:
        alias: "WM Spatial 4*4 N-1"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_4*4_2back:
        alias: "WM Spatial 4*4 N-2"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_4*4_3back:
        alias: "WM Spatial 4*4 N-3"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_Spatial_5*5_1back:
        alias: "WM Spatial 5*5 N-1"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_5*5_2back:
        alias: "WM Spatial 5*5 N-2"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_5*5_3back:
        alias: "WM Spatial 5*5 N-3"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_7*7_1back:
        alias: "WM Spatial 7*7 N-1"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_7*7_2back:
        alias: "WM Spatial 7*7 N-2"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_7*7_3back:
        alias: "WM Spatial 7*7 N-3"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_3*3_abstract_ 1back:
        alias: "WM Spatial 3*3 Abstract N-1"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_3*3_abstract_2back:
        alias: "WM Spatial 3*3 Abstract N-2"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_3*3_abstract_3back:
        alias: "WM Spatial 3*3 Abstract N-3"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_3*3_abstract_2_1back:
        alias: "WM Spatial 3*3 Abstract 2 N-1"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_3*3_abstract_2_2back:
        alias: "WM Spatial 3*3 Abstract 2 N-2"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_spatial_abstract_2_3back:
        alias: "WM Spatial 3*3 Abstract 2 N-3"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
    wm_verbal_1back:
        alias: "WM Verbal N-1"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: True
        random_baseline: 0.5
        higher_bound: 1
    wm_verbal_2back:
        alias: "WM Verbal N- 2"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: True
        random_baseline: 0.5
        higher_bound: 1
    wm_verbal_3back:
        alias: "WM Verbal N-3"
        functional: [ "working_memory" ]
        formal: [ ]
        functional_groups: [ "executive_functions" ]
        task_type: [ "open_question" ]
        backend: "playeval_framework"
        main_task: True
        random_baseline: 0.5
        higher_bound: 1


##
social_iqa:
    social_iqa:
        alias: "SocialIQA"
        backend: "harness"
        functional: [ "social_commonsense_reasoning" ]
        main_task: True
        random_baseline: 0.33
        higher_bound: 1
mmlu:
    mmlu:
        alias: "MMLU"
        backend: "harness"
        main_task: True
        random_baseline: 0.5
        higher_bound: 1
bbh_fewshot:
    bbh_fewshot:
        alias: "BBH"
        backend: "harness"
        main_task: True
metabench:
    metabench:
        alias: "Metabench"
        backend: "harness"
        main_task: True
        random_baseline: 0 # to compute (but maybe useless)
        higher_bound: 1
    metabench_arc:
        alias: "Metabench ARC"
        backend: "harness"
        main_task: False
        random_baseline: 0.25
        higher_bound: 1
    metabench_gsm8k:
        alias: "Metabench GSM8K"
        backend: "harness"
        main_task: False
        random_baseline: 0
        higher_bound: 1
    metabench_hellaswag:
        alias: "Metabench HellaSWAG"
        backend: "harness"
        main_task: False
        random_baseline: 0.25
        higher_bound: 1
    metabench_mmlu:
        alias: "Metabench MMLU"
        backend: "harness"
        main_task: False
        random_baseline: 0.25
        higher_bound: 1
    metabench_truthfulqa:
        alias: "Metabench HellaSWAG"
        backend: "harness"
        main_task: False
        random_baseline: 0.12
        higher_bound: 1
    metabench_winogrande:
        alias: "Metabench Winogrande"
        backend: "harness"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1