logiqa2:
    logiqa2:
        alias: "LogiQA 2.0"
        category: "logical_numerical_reasoning"
        backend: "lm-eval"
        main_task: True
        random_baseline: 0.25
        higher_bound: 1
        metrics_short_report: ['acc']
cladder:
    cladder:
        alias: "CLadder"
        category: "causal_reasoning"
        backend: "lm-eval"
        main_task: True
        random_baseline: 0.4927
        higher_bound: 1
        metrics_short_report: ['acc']
winogrande:
    winogrande:
        alias: "Winogrande"
        category: "commonsense_reasoning"
        backend: "lm-eval"
        main_task: True
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
ewok_minimal_pairs:
    ewok_minimal_pairs:
        alias: "EWoK Minimal Pairs"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_social:
        alias: "EWoK (Social)"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: True
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_executive:
        alias: "EWoK (Non-Social)"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: True
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_agent_properties:
        alias: "EWoK Minimal Pairs Agent Properties"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_social_relations:
        alias: "EWoK Minimal Pairs Social Relations"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_material_dynamics:
        alias: "EWoK Minimal Pairs Material Dynamics"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_physical_relations:
        alias: "EWoK Minimal Pairs Physical Relations"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_physical_interactions:
        alias: "EWoK Minimal Pairs Physical Interactions"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_physical_dynamics:
        alias: "EWoK Minimal Pairs Physical Dynamics"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_spatial_relations:
        alias: "EWoK Minimal Pairs Spatial Relations"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_quantitative_properties:
        alias: "EWoK Minimal Pairs Quantitative Properties"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_social_properties:
        alias: "EWoK Minimal Pairs Social Properties"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_social_interactions:
        alias: "EWoK Minimal Pairs Social Interactions"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    ewok_minimal_pairs_material_properties:
        alias: "EWoK Minimal Pairs Material Properties"
        category: "massive"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
eq_bench:
    eq_bench:
        alias: "EQBench"
        category: "emotional_intelligence"
        main_task: True
        backend: "lm-eval"
        random_baseline: 0
        higher_bound: 100
        metrics_short_report: ['eqbench']
lm_pragmatics:
    lm_pragmatics:
        alias: "LM-Pragmatics"
        category: "pragmatics"
        backend: "lm-eval"
        main_task: True
        random_baseline: 0.3
        higher_bound: 1
        metrics_short_report: ['acc']
    coherence:
        alias: "LM-Pragmatics Coherence"
        category: "pragmatics"
        backend: "lm-eval"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    deceits:
        alias: "LM-Pragmatics Deceits"
        category: "pragmatics"
        backend: "lm-eval"
        main_task: False
        random_baseline: 0.25
        higher_bound: 1
        metrics_short_report: ['acc']
    humour:
        alias: "LM-Pragmatics Humour"
        category: "pragmatics"
        backend: "lm-eval"
        main_task: False
        random_baseline: 0.2
        higher_bound: 1
        metrics_short_report: ['acc']
    irony:
        alias: "LM-Pragmatics Irony"
        category: "pragmatics"
        backend: "lm-eval"
        main_task: False
        random_baseline: 0.25
        higher_bound: 1
        metrics_short_report: ['acc']
    maxims:
        alias: "LM-Pragmatics Maxims"
        category: "pragmatics"
        backend: "lm-eval"
        main_task: False
        random_baseline: 0.25
        higher_bound: 1
        metrics_short_report: ['acc']
    metaphor:
        alias: "LM-Pragmatics Metaphor"
        category: "pragmatics"
        backend: "lm-eval"
        main_task: False
        random_baseline: 0.2
        higher_bound: 1
        metrics_short_report: ['acc']
    indirect_speech:
        alias: "LM-Pragmatics Indirect Speech"
        category: "pragmatics"
        backend: "lm-eval"
        main_task: False
        random_baseline: 0.25
        higher_bound: 1
        metrics_short_report: ['acc']
wm_greedy:
    wm_greedy:
        alias: "WM"
        category: "working_memory"
        main_task: False
        backend: "playpen_eval_benchmarks"
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    wm_verbal_1back_greedy:
        alias: "WM Verbal N-1"
        category: "working_memory"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    wm_verbal_2back_greedy:
        alias: "WM Verbal N-2"
        category: "working_memory"
        backend: "playpen_eval_benchmarks"
        main_task: False
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    wm_verbal_3back_greedy:
        alias: "WM Verbal N-3"
        category: "working_memory"
        backend: "playpen_eval_benchmarks"
        main_task: True
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
social_iqa:
    social_iqa:
        alias: "SocialIQA"
        category: "social_commonsense_reasoning"
        backend: "lm-eval"
        main_task: True
        random_baseline: 0.33
        higher_bound: 1
        metrics_short_report: ['acc']
mmlu:
    mmlu:
        alias: "MMLU"
        backend: "lm-eval"
        category: "massive"
        main_task: True
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
bbh_fewshot:
    bbh_fewshot:
        alias: "BBH"
        backend: "lm-eval"
        category: "massive"
        random_baseline: 0
        higher_bound: 1
        main_task: True
        metrics_short_report: ['exact_match']
ifeval:
    ifeval:
        alias: "IFEval"
        backend: "lm-eval"
        category: "extra"
        random_baseline: 0
        higher_bound: 1
        main_task: True
        metrics_short_report: ['prompt_level_strict_acc', 'inst_level_strict_acc']
llm_cognitive_flexibility_original:
    llm_cognitive_flexibility_original:
        alias: "LLM Cognitive Flexibility"
        category: "cognitive_flexibility"
        main_task: True
        backend: "playpen_eval_benchmarks"
        random_baseline: 0.8035
        higher_bound: 1
        metrics_short_report: ['acc']
    llm_cognitive_flexibility_wcst_original:
        alias: "LLM Cognitive Flexibility (WCST)"
        category: "cognitive_flexibility"
        main_task: False
        backend: "playpen_eval_benchmarks"
        random_baseline: 0.75
        higher_bound: 1
        metrics_short_report: ['acc']
    llm_cognitive_flexibility_lnt_original:
        alias: "LLM Cognitive Flexibility (LNT)"
        category: "cognitive_flexibility"
        main_task: False
        backend: "playpen_eval_benchmarks"
        random_baseline: 0.857
        higher_bound: 1
        metrics_short_report: ['acc']
llm_cognitive_flexibility_revisited:
    llm_cognitive_flexibility_revisited:
        alias: "LLM Cognitive Flexibility"
        category: "cognitive_flexibility"
        main_task: True
        backend: "playpen_eval_benchmarks"
        random_baseline: 0.8035
        higher_bound: 1
        metrics_short_report: ['acc']
    llm_cognitive_flexibility_wcst_revisited:
        alias: "LLM Cognitive Flexibility (WCST)"
        category: "cognitive_flexibility"
        main_task: False
        backend: "playpen_eval_benchmarks"
        random_baseline: 0.75
        higher_bound: 1
        metrics_short_report: ['acc']
    llm_cognitive_flexibility_lnt_revisited:
        alias: "LLM Cognitive Flexibility (LNT)"
        category: "cognitive_flexibility"
        main_task: False
        backend: "playpen_eval_benchmarks"
        random_baseline: 0.857
        higher_bound: 1
        metrics_short_report: ['acc']
simpletom:
    simpletom:
        alias: "SimpleToM"
        category: "theory_of_mind"
        main_task: False
        backend: "lm-eval"
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    simpletom-judgment-behavior-qa:
        alias: "SimpleToM (Judgment/Behavior)"
        category: "attribution_judgment"
        main_task: True
        backend: "lm-eval"
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    judgment-qa:
        alias: "SimpleToM (Judgment)"
        category: "attribution_judgment"
        main_task: False
        backend: "lm-eval"
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    behavior-qa:
        alias: "SimpleToM (Behavior)"
        category: "attribution_judgment"
        main_task: False
        backend: "lm-eval"
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
    mental-state-qa:
        alias: "SimpleToM (Mental State)"
        category: "theory_of_mind"
        main_task: True
        backend: "lm-eval"
        random_baseline: 0.5
        higher_bound: 1
        metrics_short_report: ['acc']
natural_planning:
    natural_planning_5shot:
        alias: "Natural Planning"
        category: "planning_decision_making"
        main_task: True
        backend: "lm-eval"
        random_baseline: 0
        higher_bound: 1
        metrics_short_report: ['acc']
    calendar-planning-5shot:
        alias: "Natural Planning (Calendar)"
        category: "planning_decision_making"
        main_task: False
        backend: "lm-eval"
        random_baseline: 0
        higher_bound: 1
        metrics_short_report: ['acc']
    meeting-planning-5shot:
        alias: "Natural Planning (Meeting)"
        category: "planning_decision_making"
        main_task: False
        backend: "lm-eval"
        random_baseline: 0
        higher_bound: 1
        metrics_short_report: ['acc']
    travel-planning-5shot:
        alias: "Natural Planning (Travel)"
        category: "planning_decision_making"
        main_task: False
        backend: "lm-eval"
        random_baseline: 0
        higher_bound: 1
        metrics_short_report: ['acc']
# Interactive
entity_deduction_arena:
    entity_deduction_arena:
        alias: "EDA"
        category: "interactive"
        main_task: True
        backend: "playpen_eval_benchmarks"
        random_baseline: 0
        higher_bound: 1
    entity_deduction_arena_things:
        alias: "EDA Things"
        category: "interactive"
        main_task: True
        backend: "playpen_eval_benchmarks"
        random_baseline: 0
        higher_bound: 1
    entity_deduction_arena_celebrities:
        alias: "EDA Celebrities"
        category: "interactive"
        main_task: True
        backend: "playpen_eval_benchmarks"
        random_baseline: 0
        higher_bound: 1
clembench:
    clembench:
        alias: "Interactive"
        category: "interactive"
        main_task: True
        backend: "clembench"
        random_baseline: 0
        higher_bound: 1

massive_merged:
    massive_merged:
        alias: "Static"
        category: "massive"
        main_task: True
        backend: "lm-eval"
        random_baseline: 0
        higher_bound: 1
wordle:
    wordle:
        alias: "Wordle"
        category: "interactive"
        main_task: True
        backend: "clembench"
        random_baseline: 0
        higher_bound: 1
wordle_withcritic:
    wordle_withcritic:
        alias: "Wordle (Critic)"
        category: "interactive"
        main_task: True
        backend: "clembench"
        random_baseline: 0
        higher_bound: 1
wordle_withclue:
    wordle_withclue:
        alias: "Wordle (Clue)"
        category: "interactive"
        main_task: True
        backend: "clembench"
        random_baseline: 0
        higher_bound: 1
privateshared:
    privateshared:
        alias: "Private/Shared"
        category: "interactive"
        main_task: True
        backend: "clembench"
        random_baseline: 0
        higher_bound: 1
imagegame:
    imagegame:
        alias: "Image Game"
        category: "interactive"
        main_task: True
        backend: "clembench"
        random_baseline: 0
        higher_bound: 1
referencegame:
    referencegame:
        alias: "Reference Game"
        category: "interactive"
        main_task: True
        backend: "clembench"
        random_baseline: 0
        higher_bound: 1
taboo:
    taboo:
        alias: "Taboo"
        category: "interactive"
        main_task: True
        backend: "clembench"
        random_baseline: 0
        higher_bound: 1

glue_diagnostics:
    glue_diagnostics:
        alias: "GLUE Diagnostics"
        backend: "lm-eval"
        category: "formal"
        random_baseline: 0
        higher_bound: 0.33
        main_task: True
        metrics_short_report: ['acc']
    glue_diagnostics_lexical_semantics:
        alias: "GLUE Diagnostics Lexical Semantics"
        backend: "lm-eval"
        category: "formal"
        random_baseline: 0
        higher_bound: 0.33
        main_task: True
        metrics_short_report: ['acc']
    glue_diagnostics_predicate_argument_structure:
        alias: "GLUE Diagnostics Predicate Argument Structure"
        backend: "lm-eval"
        category: "formal"
        random_baseline: 0
        higher_bound: 0.33
        main_task: True
        metrics_short_report: ['acc']
    glue_diagnostics_logic:
        alias: "GLUE Diagnostics Logic"
        backend: "lm-eval"
        category: "formal"
        random_baseline: 0
        higher_bound: 0.33
        main_task: True
        metrics_short_report: ['acc']
    glue_diagnostics_knowledge_world:
        alias: "GLUE Diagnostics Knowledge World"
        backend: "lm-eval"
        category: "formal"
        random_baseline: 0
        higher_bound: 0.33
        main_task: True
        metrics_short_report: ['acc']
    glue_diagnostics_knowledge_common_sense:
        alias: "GLUE Diagnostics Commonsense"
        backend: "lm-eval"
        category: "formal"
        random_baseline: 0
        higher_bound: 0.33
        main_task: True
        metrics_short_report: ['acc']