capabilities:
  functional: [ "commonsense_reasoning", "planning_decision_making", "logical_numerical_reasoning", "causal_reasoning","social_commonsense_reasoning", "theory_of_mind", "emotional_intelligence", "pragmatics", "working_memory"]
  formal: [ "semantics", "predicate_argument_structure", "negation", "metalinguistic" ]

groups:
    entity_deduction_arena:
        entity_deduction_arena_things:
            alias: "Entity Deduction Arena Things"
            functional: [ "strategic_reasoning" ]
            formal: [ ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "interactive" ]
            main_task: True
            backend: "playeval_framework"
            # TODO Specify Random Baseline
        entity_deduction_arena_things_celebrities:
            alias: "Entity Deduction Arena Celebrities"
            functional: [ "strategic_reasoning" ]
            formal: [ ]
            functional_groups: [ "executive_functions" ]
            task_type: [ "interactive" ]
            main_task: True
            backend: "playeval_framework"
            # TODO Specify Random Baseline